version: '3'

services:
  db:
    build: 
      context: ./postgres/
      

    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo
      - POSTGRES_PASSWORD=area51
    ports:
      - "5431:5432"
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data
    
    networks:
      - app-network
      




  todoapp:
    depends_on:
      - db
    build: 
       context: .
       
    container_name: todo-app
    restart: unless-stopped
    environment:
      - DB_USER=postgres
      - DB_PASS=area51
      - DB_NAME=todo
      - DB_HOST=db
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "80:8000"
    volumes:
      - ./:/usr/src/app
    networks:
      - app-network


  
networks:
  app-network:
    driver: bridge

